#!/bin/sh
/usr/bin/ping -4 -q -c 1 example.org > /dev/null \
	|| /usr/bin/ping -4 -q -c 1 google.com > /dev/null || exit
#pidof -q newsboat && killall newsboat
newsboat -x reload && notify-send "🗞️ rss actualizado"
